backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "config"
    label: "Site Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "content/site_config.json"
        description: "General site settings"
        fields:
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Message from the founder"
            name: "message_from_founder"
            widget: "markdown"
          - label: "Popular courses"
            name: "popular_courses"
            widget: "list"
            summary: "{{fields.course}}"
            fields: { label: Course, name: course, widget: "string" }
          - label: "Statstics"
            name: "site_stats"
            widget: "list"
            summary: "{{fields.name}} - {{fields.count}}"
            fields:
              - {label: Text, name: name, widget: string}
              - {label: Count, name: count, widget: string}
          - label: "Testimonials"
            name: "site_testimonials"
            widget: "list"
            summary: "{{fields.name}} - {{fields.count}}"
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Avatar, name: avatar, widget: image}
              - {label: Course, name: course, widget: string}
              - {label: Testimonial, name: testimonial, widget: markdown}
  - name: "about"
    label: "About"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "About"
        file: "content/about.json"
        description: "Configure About Page"
        fields:
          - label: "Description"
            name: "description"
            widget: "markdown"
          - label: "Mission"
            name: "mission"
            widget: "markdown"
          - label: "Vision"
            name: "vision"
            widget: "markdown"
  - name: "courses"
    label: "Courses"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Courses"
        file: "content/courses.json"
        description: "Configure Courses Page"
        fields:
          - label: "Courses"
            name: "courses"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Amount, name: amount, widget: string}
              - {label: Period, name: period, widget: string}
              - {label: Icon, name: image, widget: image}
              - label: Features
                name: what_will_you_get
                widget: object
                fields:
                  - {label: Feature, name: feature, widget: string}
  - name: "test_series"
    label: "Test Series"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Test Series"
        file: "content/test_series.json"
        description: "Configure Test Series Page"
        fields:
          - label: "Test Series"
            name: "test_series"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Monthly Price", name: "monthly_price", widget: "string"}
              - {label: "Yearly Price", name: "annually_price", widget: "string"}
              - {label: "Icon", name: "image", widget: "image", default: "images/uploads/test_default.png"}
              - label: "Features"
                name: "what_will_you_get"
                widget: "object"
                fields:
                  - {label: "Feature", name: "feature", widget: "string"}
  - name: "faculties"
    label: "Faculties"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Faculties"
        file: "content/faculty.json"
        description: "Configure Faculties Page"
        fields:
          - label: "Faculties"
            name: "faculties"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Designation, name: designation, widget: string}
              - {label: Email, name: email, widget: string}
              - {label: Image, name: image, widget: image}
              - {label: Color, name: color, widget: string}
  - name: "gallery"
    label: "Gallery"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Gallery"
        file: "content/gallery.json"
        description: "Configure Gallery Page"
        fields:
          - label: "Gallery"
            name: "gallery"
            widget: "list"
            summary: "{{fields.image}}"
            fields:
              - {label: Image, name: image, widget: image}
  - name: "contacts"
    label: "contacts"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Contacts"
        file: "content/contacts.json"
        description: "Configure Contacts Page"
        fields:
          - label: "Contacts"
            name: "contacts"
            widget: "list"
            summary: "{{fields.campus_name}}"
            fields:
              - {label: "Campus Name", name: campus_name, widget: string}
              - {label: "Whatsapp No", name: whatsapp_no, widget: string}
              - {label: "Address", name: address, widget: markdown}