backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "config"
    label: "Site Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "content/site_config.json"
        description: "General site settings"
        fields:
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Message from the founder"
            name: "message_from_founder"
            widget: "markdown"
          - label: "Popular courses"
            name: "popular_courses"
            widget: "list"
            summary: "{{fields.course.course}}"
            field:
              label: course
              name: course
              widget: "string"
          - label: "Statstics"
            name: "site_stats"
            widget: "list"
            summary: "{{fields.name}} - {{fields.count}}"
            fields:
              - {label: Text, name: name, widget: string}
              - {label: Count, name: count, widget: string}
  - name: "about"
    label: "About"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "About"
        file: "content/about.json"
        description: "Configure About Page"
        fields:
          - label: "Description"
            name: "description"
            widget: "markdown"
          - label: "Mission"
            name: "mission"
            widget: "markdown"
          - label: "Vision"
            name: "vision"
            widget: "markdown"
  - name: "courses"
    label: "Courses"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Courses"
        file: "content/about.json"
        description: "Configure About Page"
        fields:
          - label: "Course"
            name: "course"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Amount, name: amount, widget: string}
              - {label: Period, name: peroid, widget: string}
              - label: Features
                name: what_will_you_get
                widget: list
                field:
                  label: Feature
                  name: feature
                  widget: string